name: flaury_business
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  hooks_riverpod: ^2.4.9
  flutter_spinkit:
  smooth_page_indicator:
  flutter_svg: ^2.0.10+1
  flutter_animate:
  device_preview: ^1.1.0
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.2
  flutter_native_splash: ^2.4.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
